name: Build and Release APK

on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build APK with Gradle
        run: ./gradlew assembleRelease --stacktrace || ./gradlew assembleDebug

      - name: Create Release and Upload APK
        uses: softprops/action-gh-release@v2
        with:
          files: |
            app/build/outputs/apk/**/*.apk
            chrome-extension/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
